name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install client dependencies and build client
        run: |
          cd client
          npm install
          npm run build
          cd ..

      - name: Move client build to server/src
        run: |
          mkdir -p server/src
          cp -a client/dist/. server/src

      - name: Install server dependencies
        run: |
          cd server
          npm install
          cd ..

      - name: Zip server for deployment
        run: zip -r server.zip server

      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-app
          path: server.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download server artifact
        uses: actions/download-artifact@v2
        with:
          name: server-app
          path: .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-todo-app-pipeline'
          package: server.zip
